server:
  host: 192.168.1.81
  port: 18034
  username: admin
  password: password
  zones:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
    - 32
    - 33
    - 34
    - 35
    - 36
    - 37
    - 38
    - 39
    - 40
  showUnnamedZones: true
  areas: 1
  delay: 200
  polling_status: 5000
  features:
    - armDisarm
    - sensors
    - events
    - bypass
    - zoneNames
mqtt:
  host: 192.168.1.82
  port: "1883"
  username: admin
  password: password
  clientId: ialarm-mqtt
  cache: 5m
  retain: true
verbose: false
name: Alarm
topics:
  availability: ialarm/alarm/availability
  alarm:
    command: ialarm/alarm/area/${areaId}/set
    state: ialarm/alarm/state
    event: ialarm/alarm/event
    bypass: ialarm/alarm/zone/${zoneId}/bypass
    discovery: ialarm/alarm/discovery
    resetCache: ialarm/alarm/resetCache
    configStatus: ialarm/alarm/configStatus
  sensors:
    topicType: state
    state: ialarm/sensors/state
    zone:
      state: ialarm/sensors/zone_${zoneId}
      alarm: ialarm/sensors/zone_${zoneId}/alarm
      active: ialarm/sensors/zone_${zoneId}/wirelessLoss
      lowBattery: ialarm/sensors/zone_${zoneId}/lowbat
      fault: ialarm/sensors/zone_${zoneId}/fault
payloads:
  alarmAvailable: online
  alarmNotvailable: offline
  alarmDecoder:
    armAway:
      - armAway
      - armedAway
      - armed_away
      - arm_away
      - AA
      - AwayArm
    armHome:
      - armHome
      - armedHome
      - armed_home
      - arm_home
      - SA
      - HomeArm
      - StayArm
      - armStay
      - armedStay
      - arm_stay
      - armed_stay
    disarm:
      - disarm
      - disarmed
      - D
    cancel:
      - cancel
      - canceled
      - C
    triggered:
      - trigger
      - triggered
      - T
  alarm:
    armAway: armed_away
    armHome: armed_home
    disarm: disarmed
    cancel: cancel
    triggered: triggered
  sensorOn: "1"
  sensorOff: "0"
hadiscovery:
  enabled: true
  discoveryPrefix: homeassistant
  topics:
    alarmConfig: ${discoveryPrefix}/alarm_control_panel/ialarm_${areaId}/config
    eventsConfig: ${discoveryPrefix}/sensor/ialarm/events/config
    connectionConfig: ${discoveryPrefix}/binary_sensor/ialarm/connection/config
    sensorConfig: ${discoveryPrefix}/binary_sensor/ialarm_zone_${zoneId}/fault/config
    sensorBatteryConfig: ${discoveryPrefix}/binary_sensor/ialarm_zone_${zoneId}/battery/config
    sensorAlarmConfig: ${discoveryPrefix}/binary_sensor/ialarm_zone_${zoneId}/alarm/config
    sensorConnectivityConfig: ${discoveryPrefix}/binary_sensor/ialarm_zone_${zoneId}/connectivity/config
    bypassConfig: ${discoveryPrefix}/switch/ialarm/${zoneId}/config
    clearCacheConfig: ${discoveryPrefix}/switch/ialarm/clear_cache/config
    clearDiscoveryConfig: ${discoveryPrefix}/switch/ialarm/clear_discovery/config
    clearTriggeredConfig: ${discoveryPrefix}/switch/ialarm/clear_triggered/config
  zoneName: Zone
  faultName: Motion
  batteryName: Battery
  alarmName: Alarm
  connectivityName: Connectivity
  cleanCacheName: Clean cache
  cleanCacheDiscoveryName: Clean discovery
  cleanCacheTriggeredName: Clean triggered
  commStatusName: Communication status
  bypassName: Bypass
  bypassIcon: mdi:lock-open
  eventName: Last event
  eventIcon: mdi:message-alert
  alarm_qos: 2
  sensors_qos: 0
  code: ""
  zones:
    "0":
      device_class: safety
    "1":
      device_class: door
    "2":
      device_class: window
    "3":
      device_class: motion
    "4":
      device_class: safety
    "5":
      device_class: gas
    "6":
      device_class: smoke
    "7":
      device_class: lock
    problem:
      zone bypass: safety
      zone fault: problem
      wireless detector low battery: battery
      wireless detector loss: connectivity
    default:
      device_class: safety
zones: []
