name: build-release

env:
  REPO_NAME: ${{ github.event.repository.name }}
  BUILD_TAG: 'latest'

on:
  push:
    branches: 'master'
    tags: '*'
    paths:
      - '.github/workflows/dockerimage.yml'
      - 'Dockerfile'

jobs:
  npm:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}  
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.prepare.outputs.tag_name }}
      version: ${{ steps.prepare.outputs.version }}
      build_date: ${{ steps.prepare.outputs.build_date }}
    steps:
      - name: Prepare
        id: prepare
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            echo "tag_name=${TAG}" >> $GITHUB_OUTPUT
            echo "version=${TAG%-*}" >> $GITHUB_OUTPUT
          else
            echo "tag_name=snapshot" >> $GITHUB_OUTPUT
            echo "version=snapshot" >> $GITHUB_OUTPUT
            echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          fi 
  release:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - run: 'echo Building ${{ env.REPO_NAME }} with tag=${{needs.prepare.outputs.tag_name}} version=${{needs.prepare.outputs.version}} Build Date=${{needs.prepare.outputs.build_date}}'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ env.BUILD_TAG }},${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ needs.prepare.outputs.version }}
          